import type { Metadata } from "next";
import { Roboto  } from "next/font/google";
import "./globals.css";

// const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] }); // Customize the font if needed

export const metadata: Metadata = {
  title: "Gulf Mobile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
